# Generated by Django 5.0.4 on 2024-04-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='name',
            new_name='topic',
        ),
    ]
