# Generated by Django 5.0.4 on 2024-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_posed_date_talk_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
